server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: AuthenticationService
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/authentication_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Krishna}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${MAIL_USERNAME:XXXXXXXXXXXXX}
    password: ${MAIL_PASSWORD:XXXXXXXXXXXXX}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    spring:
      security: DEBUG

app:
  jwt-secret: JWTSecreteKey
  jwt-expiration-milliseconds: 3600000 # 1 hour in milliseconds
  jwt-refresh-expiration-milliseconds: 86400000 # 1 day in milliseconds
