server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://b2b-webapp-postgre-db-dev.cbca0wk6w38y.ap-south-2.rds.amazonaws.com:5432/postgredb1
    username: postgres
    password: Tuesday2025$$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: zucitechtest@gmail.com
    password: lpzdcporyvtrlowj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    spring:
      security: DEBUG

app:
  jwt-secret: JWTSecreteKey
  jwt-expiration-milliseconds: 3600000 # 1 hour in milliseconds
  jwt-refresh-expiration-milliseconds: 86400000 # 1 day in milliseconds
